### ISSUE TITLE
Security Vulnerability - XSS

### ISSUE THREAD

**Issue by Castilh0** [inrupt/solid-style-guide#52]
**About**

Hi, by using your design library, I came upon an **XSS** ( Cross-Site Scripting ) vulnerability. The issue occurs at the ?cat= parameter. An attacker could insert an XSS payload as the value of the parameter and code would be executed.

The exploit would look like this :
`https://design.inrupt.com/atomic-core/?cat="><svg/onload=confirm(document.domain)>`
( This only executes a PopUp alert saying the domain, so don't worry)

This means everyone that is using your library is vulnerable to this security issue.
This also means, that your website is vulnerable to this issue as you can confirm by going into the URL above ( Use **Firefox browser** for this, Google Chrome as protection against XSS )

**Fix**
Sanitize user input when reflecting on the page. Such as using `htmlspecialchars();` PHP function every time we are reflecting user input is a good habit to prevent XSS. 

Thank you for your time, Castilho.

**Comment by Castilh0** [comment]
It appears that only the parameter ?cat= is vulnerable but all the user input that is reflected is vulnerable.
Please fix this ASAP, because you are letting the people that are using your library vulnerable to malicious attacks.

**Comment by michielbdejong** [comment]
Thanks for reporting this, sorry it didn't get picked up earlier.
Note that this only affects the PHP-generated (but otherwise static) design.inrupt.com example site, not the style guide itself.

Since that site has no moving parts itself, there's not much harm in it but it's definitely using PHP in the wrong way, so I applied your suggested fix in #69. Thanks a lot!
